# 图表种类

** 数据可视化的步骤**

1. 了解需求，了解面向的对象，了解观众
2. 了解数据，各个数据的含义
3. 确定所需图表
4. 确定图表的组合结构

## 相关关系

本章讲述了如何在多个变量中找寻关联性，但同时也从更加宽泛的意义上阐述了关系的实质。从分布观察事物作为整体是如何彼此联系的，在分布中寻找模式、剔除异常值，然后考虑整件事的上下文背景。如果在这个过程中你发现了一些有趣的地方，尝试通过数据的上下文背景找到可能合理的解释。

### 散点图

相关性，聚类

### 气泡图

用额外的点的大小来代表另一个字段的颜色

### 直方图

分布状况

### 对照和比较

多图对比，多个子图进行比较

## 比较关系

也许你的数据中包含多种变量，但你希望把所有对象（比如人或地点）进行分组，然后找出其中最出众的或者说异常值。你希望看到每一个变量间的差异，也希望看到所有变量间的差异。两个篮球运动员的场均得分可能是天壤之别，但他们的场均篮板、抢断和出场时间却可能非常接近。我们需要找出事物间的差异，但也不要忘记相似性和背后的关联性，就和那些体育评论员一样。

### 热图

矩形结构

### 箱线图 

分析差异点

## 比例关系

关心比例的分配.

比例分布数据和其他数据类型的主要区别在于它们体现的是整体中的各个部分。每一个单独的数值都有其意义，而各部分相加得到的子集或者总和也是如此。我们的可视化成果应该体现出这些方面。如果数据并不多，那么饼图可能最适合你。当然也可以用面包圈图，不过要稍加小心。如果有多个类别的多个数值，可以考虑堆叠柱形图，而非多个饼图。如果你想探索其中随时间而变化的模式，则可以使用堆叠面积图，或者用传统的时间序列图。有了这些作为基础，你的比例图一定会出类拔萃。

### 饼图

局限性：不宜展示太多部分，容易显示不清，当然可以用技巧处理

* 良好组织数据，不要将一个饼图分成太多块。

### 环形图

通过弧形长度来进行数值的衡量,中间可以放入说明，地点时间等

同样也是不能画太多块

### 比例堆叠图

一般是各个项目的各个种类的比例或数量的堆叠，比如各个项目的投票。投票中各个类目的堆叠的比例是否显示。

### 层级和矩形

比如树状图和热力关系图就是层级和矩形图的一种代表

### 带时间的比例关系

比如各个月的销售额以堆叠图来展示

## 时间序列

## 空间关系

## 绘制建议与技巧

* 可以适当的加一些文字标注


